### ISSUE TITLE
API EXPIRED

### ISSUE THREAD

**Issue by Laende** [vingtfranc/LoLAnalyzer#6] opened 2018-06-11 20:34 UTC
Hi! Ran the configupdater successfully, but getting the error mentioned in title even with a newly generated API key, also it ends with the same problem as the issue mentioned in #2. I've updated RunAll.py to:

    m = Modes.ABR_TJMCS_Mode(['8.10', '8.11'])

I've also tried deleting the extracted folder and file. 

Other suggestions to try? 

![1](https://user-images.githubusercontent.com/17346078/41256798-f85785ee-6dca-11e8-907c-348517e567b5.PNG)
![2](https://user-images.githubusercontent.com/17346078/41256797-f8357044-6dca-11e8-9844-4f4410ab3ffa.PNG)

**Comment by VRichardJP** [comment] 2018-06-11 21:47
I guess the API from Riot may have changed a bit. I'll check this out.

**Comment by Laende** [comment] 2018-06-14 12:41
Status? :)

**Comment by VRichardJP** [comment] 2018-06-14 13:26
Soon™
Sorry I'm very busy atm, I'll try to check this weekend maybe ^^

**Comment by VRichardJP** [comment] 2018-06-17 02:32
As I guessed, Riot's API has changed a little bit. Normally, requesting a page that does not exist should return a 404 error, but it seems they have simply restricted the access to the old API, hence the "API-KEY has EXPIRED" error msg.
I pushed a fix. I was able to download games from kr server dia league with this.
Tell me if you have another issue.

PS: set DEBUG to False in InterfaceAPI.py if you don't want to be flooded by all the msg

**Comment by Laende** [comment] 2018-06-17 14:36
These errors occasionally appear. Any idea?

![skjermbilde](https://user-images.githubusercontent.com/17346078/41508954-9035a1a4-724c-11e8-89f1-e4487513322a.PNG)

EDIT: Seems to be a windows bug.

Also, I'd like to train with GPUs. Is it as simple as to just install tensorflow-gpu? No need to add any imports / edit few lines of code?

Thanks for the help so far!

**Comment by VRichardJP** [comment] 2018-06-17 15:15
This is a strange bug indeed, caused by a recent Windows 10 update <3 (https://bugs.python.org/issue32245)
If this is the only print to be concerned, you can either comment it or do something like this:
```
try:
    print(...)
except OSError as e:
    pass
```
If this is not the only one, well you can do something like this:
- replace all 'print' with 'myprint'
- add this function after the imports
```
def myprint(*args, **kargs):
    try:
        print(*args, **kargs)
    except OSError as e:
        pass
```

As for the GPU part, you only need to install tensorflow-gpu. Tensorflow will tell you which hardware has been detected once you're at the training part.
If you have already installed tensorflow, remove it first to make sure you will only have gpu version:
```
pip3 uninstall tensorflow
pip3 install tensorflow-gpu
```

**Comment by Laende** [comment] 2018-06-18 17:38
After getting the players this happens: 

![skjermbilde1](https://user-images.githubusercontent.com/17346078/41552499-3580758e-732f-11e8-84c3-7105457a0326.PNG)
![skjermbilde2](https://user-images.githubusercontent.com/17346078/41552501-359fbf3e-732f-11e8-9818-d340d13940e7.PNG)

**Closed as completed** 2018-06-18 20:24 UTC

**Comment by VRichardJP** [comment] 2018-06-18 20:36
A fix has been pushed

Once again something new from the API:
Riot does not save player's role/lane from the roles you are assigned in the lobby because of the possible role/lane swap. Instead, they have a secret algorithm which goal is to deduce what role/lane each player had by looking at some in-game stats (for example, the player average (x,y) position in the first 10 minutes).
Until now, this algorithm has always tagged players as either 'TOP', 'JUNGLE', 'MIDDLE' or 'BOTTOM'. But apparently, a new lane has appeared recently in the rift named 'NONE' :)
